### ISSUE TITLE
请问能否出一个使用 Consul 的选项

### ISSUE THREAD

**Issue by ioer2008** [AClumsy/Orleans.MultiClient#1]

**Comment by lfzm** [comment]
@ioer2008  可以配置 Consul哦，
```
opt.Configure = (b =>
   {
            b.UseLocalhostClustering(gatewayPort: 30001);
  });
```
把 ` b.UseLocalhostClustering(gatewayPort: 30001);` 替换成consul就可以了。

**Comment by ioer2008** [comment]
多谢!

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: 阿凌 <notifications@github.com>
发送时间: Thursday, December 12, 2019 9:44:21 PM
收件人: lfzm/Orleans.MultiClient <Orleans.MultiClient@noreply.github.com>
抄送: 郭军 <ioer@live.com>; Mention <mention@noreply.github.com>
主题: Re: [lfzm/Orleans.MultiClient] 请问能否出一个使用 Consul 的选项 (#1)


@ioer2008<https://github.com/ioer2008> 可以配置 Consul哦，

opt.Configure = (b =>

   {

            b.UseLocalhostClustering(gatewayPort: 30001);

  });



把 b.UseLocalhostClustering(gatewayPort: 30001); 替换成consul就可以了。

―
